version: 2

sources:
  - name: twitter_model
    schema : raw
    tables:
    - name: t_twitter_postgresql
      columns:
        - name: c_id
          description: "The primary key for this table"
          tests:
            - unique
            - not_null
        - name: c_text
          description: "Tweet text as string"
          tests:
            - not_null
        - name: c_created_at
          description: "Timestamp as string"
        - name: c_loaded_at
          description: "timestamp of loading the row"
      loaded_at_field: c_loaded_at
      freshness:
        warn_after: {count: 1, period: hour}
        error_after: {count: 4, period: hour}
