
version: 2

models:
  - name: v_twitter_postgresql
    columns:
      - name: c_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: c_text
        description: "Tweet text"
