version: 2

sources:
  - name: twitter_model
    schema : raw
    tables:
    - name: t_twitter_postgresql
      columns:
        - name: c_id
          description: "The primary key for this table"
          tests:
            - unique
            - not_null
        - name: c_text
          description: "Tweet text as string"
          tests:
            - not_null
        - name: c_created_at
          description: "Timestamp as string"
          loaded_at_field: c_created_at
          freshness:
            warn_after: {count: 12, period: hour}
            error_after: {count: 24, period: hour}
